
import React, { useState } from 'react';
import { generateImage } from '../services/gemini';

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [result, setResult] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    if (!prompt.trim() || loading) return;
    setLoading(true);
    try {
      const url = await generateImage(prompt);
      setResult(url);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!result) return;
    const link = document.createElement('a');
    link.href = result;
    link.download = `rishu-ai-gen-${Date.now()}.png`;
    link.click();
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold bg-gradient-to-r from-blue-400 to-emerald-400 bg-clip-text text-transparent">AI Art Generator</h1>
        <p className="text-white/60">Turn your ideas into visual masterpieces with Rishu AI</p>
      </div>

      <div className="max-w-2xl mx-auto glass p-8 rounded-3xl space-y-6">
        <div className="space-y-4">
          <label className="block text-sm font-medium text-white/70">Enter your creative prompt</label>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="A futuristic city with purple sky and floating cars..."
            className="w-full h-32 bg-white/5 border border-white/10 rounded-2xl p-4 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500/50 transition-all resize-none"
          />
          <button
            onClick={handleGenerate}
            disabled={!prompt.trim() || loading}
            className="w-full py-4 bg-gradient-to-r from-emerald-600 to-blue-600 rounded-2xl font-bold flex items-center justify-center gap-2 hover:opacity-90 disabled:opacity-50 transition-all group"
          >
            {loading ? (
              <i className="fa-solid fa-circle-notch animate-spin"></i>
            ) : (
              <>
                <i className="fa-solid fa-wand-magic-sparkles group-hover:rotate-12 transition-transform"></i>
                Generate Artwork
              </>
            )}
          </button>
        </div>

        {result && (
          <div className="space-y-4 pt-4 border-t border-white/10 animate-in zoom-in-95 duration-300">
            <div className="relative group rounded-2xl overflow-hidden border border-white/10">
              <img src={result} alt="Generated" className="w-full aspect-square object-cover" />
              <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-4">
                <button 
                  onClick={handleDownload}
                  className="w-12 h-12 rounded-full bg-white text-black flex items-center justify-center hover:scale-110 transition-transform"
                >
                  <i className="fa-solid fa-download"></i>
                </button>
              </div>
              {/* Internal Watermark */}
              <div className="absolute bottom-4 right-4 text-white/50 text-[10px] font-bold uppercase tracking-widest bg-black/20 px-2 py-1 rounded backdrop-blur-sm">
                Generated by Rishu AI
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ImageGenerator;
